### PR TITLE
resolve #11 add custom log fn

### LINKED ISSUE #11: Advanced loggers
It would be nice to use `Tensorboard` or any other advanced logging tool with `evojax`. 
Looks like it should be straightforward to allow the user to implement a `log_reward` function that could be passed to the trainer.

I'm willing to implement this in a PR.

### PR DESCRIPTION
**Pull request by danielgafni**

### CODE REVIEW

**Comment by danielgafni** [comment]
May be better to only ask for one function and pass an additional argument into the function: stage="train"|"test"

**Comment by lerrytang** [comment]
Can you fix the missing CLA error below first? I'll review the PR after that.

**Comment by danielgafni** [comment]
@lerrytang done!

**Comment by lerrytang** [comment]
Thanks for the PR, can you give example code of supplying a tensorboard log function?
This code serves as both a test and is something mentioned in #11 .
You can modify one of the examples (e.g., mnist or cartpole).

**Comment by danielgafni** [comment]
Should I add some actual code or can it be documentation? 

Some problems that arise around the example code:

 - does the user have tensorflow (or pytorch) installed? should we throw a warning or an error if tensorboard is not found?
 - the logging function needs to access the tensorboard `Summary` object
 - if using tensorflow's tensorboard implementation the logging function has to be inside a `with` statement:
 ```python
with writer.as_default():
   def log_scores_fn():
        pass

    trainer.run()
```
- pytorch's tensorboard implementation has different syntax (and doesn't require a `with` statement)

It might be better to describe this code in a documentation section rather than modify the example.
Or I could make a separate example `.py` file with strict requirements for tensorflow or pytorch installation.

**Comment by lerrytang** [comment]
I'd prefer some actual code that proves the PR works, on top of that, extra documentation is better.
As for the problems w.r.t the example code, it is the logging function provider's responsibility to address them.
If the logging function depends on something else, can we enclose it? Something like:
```python
# Just an example, not tested.
def get_logging_fn(writer):
    def fn(fn_args):
        with writer.as_default():
            do_stuff()
    return fn
trainer = Trainer(logging_fn=get_logging_fn(tf_writer), ...)
```

**Comment by danielgafni** [comment]
I just discovered `flax` provides `tensorboard` too! It's already in evojax dependencies, probably we should use it?

**Comment by danielgafni** [comment]
hey @lerrytang, any update on this?

**Comment by lerrytang** [comment]
Hi, apologies for the delay.

I tested the PR but it has some problems:
1. With no additional packages installed, it gives a warning message `Please install either tensorflow or pytorch to log the rewards to tensorboard`. This is ok.
2. However, after installing pytorch, I still get this message.
3. After installing tensorboard, I get an error complaining about `AttributeError: module 'distutils' has no attribute 'version'`. This is due to distutils change and can be easily fixed, however, this adds an extra workload to the users.

I suggest the following modifications:
1. Change the warning message. It seems installing pytorch and tensorboard suffices.
2. In `evojax.util`, can you catch distutils error (`AttributeError: module 'distutils' has no attribute 'version'`) and print out the fix for the users? (e.g., modify `torch/utils/tensorboard/__init__.py`: add `from distutils.version import LooseVersion` and comment out `LooseVersion = distutils.version.LooseVersion`)

Again, sorry for the delay and thank you for the contribution.

**Comment by danielgafni** [comment]
This is weird. Looks like you installed an old pytorch version. Looks like this bug has been fixed a year ago: https://github.com/pytorch/pytorch/pull/69904

what is your pytorch version?

**Comment by danielgafni** [comment]
Fixed the warning to mention the `tensorboard` package too.

**Pull request merged**
