### PR TITLE
Native implementation in JAX of Augmented Random Search 

### PR DESCRIPTION
**Pull request by EdoardoPona**
## Test results 
**Note** for MNIST I halved the batch size and doubled the iterations due to memory issues. 
|                          | Benchmark                   | Params   | Results (avg.) |
| ----------------|-----------------------|----------|------------- |
| CartPole (easy) | 900 (max_iter=1000)  | [Link](configs/ARS_native/cartpole_easy.yaml)| 910        |
| CartPole (hard) | 600 (max_iter=2000)  | [Link](configs/ARS_native/cartpole_hard.yaml) | 558.02       |
| MNIST | 0.90 (max_iter=4000)  | [Link](configs/ARS_native/minst.yaml) | 0.92       |
| Brax Ant | 3000 (max_iter=700)  | [Link](configs/ARS_native/brax_ant.yaml) | 4129.83        |
| Waterworld |  6 (max_iter=2000) |[Link](configs/ARS_native/waterworld.yaml) | 7.29 | 
| Waterworld (MA) |  2 (max_iter=2000) | [Link](configs/ARS_native/waterworld_ma.yaml) | 1.68 |

### CODE REVIEW

**Comment by lerrytang** [comment]
Hi, thank you for sending the PR.
We will proceed to review after you fix the lint/test errors.

**Comment by alantian** [comment]
Hey @EdoardoPona thanks for your contribution! 

Would you mind also including the the content of the test result table you show here to `scripts/benchmarks/Readme.md` in PR (as modified files)?

**Comment by EdoardoPona** [comment]
Done!

**Comment by lerrytang** [comment]
@EdoardoPona Thanks for your contribution!
Would you like to send a pr to update this [page](https://github.com/google/evojax/tree/main/evojax/algo/README.md)?

**Pull request merged**
